### PR TITLE
Fix archived vault migration during Hub upgrade

### LINKED ISSUE #269: After upgrade 1.2.2 -> 1.3.3, archived vault can't be unarchived
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

After upgrade 1.2.2 -> 1.3.3, archived vault can't be unarchived

### System Setup

```markdown
- Hub: 1.3.3 (before was: 1.2.2)
- Keycloak: 23.0.7
- Cryptomator (Desktop/Android/iOS): independent
```

### Steps to Reproduce

1. [Running on Hub version 1.2.2]
2. Archive a vault
3. [Upgrade to Hub version 1.3.3]
4. Claim ownership of archived vault with vault password
5. Click on vault to manage it

### Expected Behavior

Vault management UI is shown with possibility to unarchive vault.

### Actual Behavior

Vault management UI is shown as if I would not be owner of the vault (see screenshot)
Screenshot 2024-04-11 145835

### Reproducibility

Always

### Relevant Log Output

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SailReal**
Posting new access-tokens does not harm for archived vaults. Hard and soft boundaries are still respected.

Fixes #269

## Summary by CodeRabbit

- **Bug Fixes**
	- Removed restrictions on accessing archived vaults, allowing users to access their archived content without limitations.
	- Updated the response behavior for accessing archived vaults, ensuring users receive a successful status, enhancing usability.

### CODE REVIEW

File: backend/src/test/java/org/cryptomator/hub/api/VaultResourceTest.java [hunk 1]
```diff
@@ -162,10 +162,10 @@ public void testUnlockArchived2() {
 		}
 
 		@Test
-		@DisplayName("GET /vaults/7E57C0DE-0000-4000-8000-00010000AAAA/access-token returns 403 for archived vaults with evenIfArchived set to true")
+		@DisplayName("GET /vaults/7E57C0DE-0000-4000-8000-00010000AAAA/access-token returns 200 for archived vaults with evenIfArchived set to true")
 		public void testUnlockArchived3() throws SQLException {
 			when().get("/vaults/{vaultId}/access-token?evenIfArchived=true", "7E57C0DE-0000-4000-8000-00010000AAAA")
-					.then().statusCode(403);
+					.then().statusCode(200);
 		}
```
Comment (overheadhunter) [inline backend/src/test/java/org/cryptomator/hub/api/VaultResourceTest.java:169]: Why did the old test succeed? 😭

**Review by overheadhunter — APPROVED** [review]

File: backend/src/test/java/org/cryptomator/hub/api/VaultResourceTest.java (hunk 1 above)
Comment (SailReal) [reply backend/src/test/java/org/cryptomator/hub/api/VaultResourceTest.java:169]: Quiet exactly for the same reason described in the bug report: In the [testGrantAccessArchived](https://github.com/cryptomator/hub/pull/270/files#diff-26d7286dcd2fe62fc0616f129b85cc729ce7a5532a3c85c64d2385dd6c717942R384), the access-token wasn't added because [this vault is archived](https://github.com/cryptomator/hub/blob/develop/backend/src/test/resources/org/cryptomator/hub/flyway/V9999__Test_Data.sql#L42-L45) and then the `GET /vaults/{vaultId}/access-token?evenIfArchived=true` resource throws a [ForbiddenException](https://github.com/cryptomator/hub/blob/develop/backend/src/main/java/org/cryptomator/hub/api/VaultResource.java#L327) (403).
